### PR TITLE
add item.lua to participating libraries

### PR DESCRIPTION
**Pull request by Wozzy06**

### CODE REVIEW

**Comment by Wozzy06** [comment]
tell me if there's something wrong !

**Comment by tst2005** [comment]
Hello,

I read the use of `require "item"` at https://github.com/Wozzy06/lua-libs/blob/master/lua-libs/src/oop/item-commons.lua#L1

I recommend to use `oop.item` like shown in [github.com/Wozzy06/lua-libs/](https://github.com/Wozzy06/lua-libs/).
IMHO the use of `item` for the class system module is a bad idea.

my suggested change :
```diff
-local class = require 'item'
+local class = require 'oop.item'
```
Regards,

**Comment by Wozzy06** [comment]
it's done !

**Comment by bartbes** [comment]
Your implementation doesn't seem to pass the tests (yet):

```Testing implementation: oop.item-commons
  Test Creating a class:
      SUCCESS
  Test Inheritance:
      FAIL: tests.lua:33: assertion failed!
  Test Existence of common.class:
      SUCCESS
  Test Existence of common.instance:
      SUCCESS
  Test Initializer:
      FAIL: tests.lua:46: assertion failed!
  Test Initializer available in derived classes:
      FAIL: tests.lua:62: assertion failed!
  Test Self-test:
      FAIL: tests.lua:66: Tests work.
  Test Calling members:
      SUCCESS
  Test Instantiation:
      SUCCESS
  Test Accessing members:
      SUCCESS
  Test Inherited Initializer:
      FAIL: tests.lua:54: assertion failed!
  Summary:
    Failed: 4
    Out of: 10
    Rate: 60%
    IMPLEMENTATION DID NOT PASS
```

Looking at the code I'm not sure it supports constructors/initializers at all?

**Comment by Wozzy06** [comment]
it's fixed ! =)

**Comment by bartbes** [comment]
Thank you for the pull request, and of course thanks for implementing class commons in your library.

**Comment by Wozzy06** [comment]
it's a good idea, thanks =)

**Pull request merged**
